// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtocsvhashfgrhnonrsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10b2Nzdmhhc2hmZ3Jobm9ucnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjY4MzYsImV4cCI6MjA1NzY0MjgzNn0.Ymdl4CvJ6e5Qk7mWi2sJ9t0ZoxZRj2j1W-EXGlwFLXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);